name: PlayerSpeed
version: 1.1
author: Zelytra
main: fr.zelytra.playerspeed.main
api-version: 1.16
commands: 
  ping:
    description: ping pong
    permission: playerspeed.ping
  speed:
    description: Change player speed
    permission: playerspeed.speed
permissions:
  playerspeed.*:
    default: op
    children:
      playerspeed.ping: true
      playerspeed.speed: true
